name: Get Polymarket Positions

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  get-positions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py-clob-client requests
      
      - name: Create position script
        run: |
          echo '#!/usr/bin/env python3' > get_positions.py
          echo 'import os' >> get_positions.py
          echo 'import json' >> get_positions.py
          echo 'import time' >> get_positions.py
          echo 'import requests' >> get_positions.py
          echo 'from py_clob_client.client import ClobClient' >> get_positions.py
          echo 'from py_clob_client.constants import POLYGON' >> get_positions.py
          echo '' >> get_positions.py
          
          echo 'def load_api_credentials():' >> get_positions.py
          echo '    """加载API凭据"""' >> get_positions.py
          echo '    return {' >> get_positions.py
          echo '        "apiKey": "4f812fe9-b869-c71c-7afb-08f36a0365eb",' >> get_positions.py
          echo '        "secret": "TW2vuAaOqb1cnfS2OJvnAM-LvLNUMIAurWi65BPco_I=",' >> get_positions.py
          echo '        "passphrase": "bebaa3341759979518ec045595847d64f5b826413b0cdb485d46bd84fa0c951b"' >> get_positions.py
          echo '    }' >> get_positions.py
          echo '' >> get_positions.py
          
          echo 'def get_client_info():' >> get_positions.py
          echo '    """初始化客户端并获取详细信息"""' >> get_positions.py
          echo '    # 配置客户端' >> get_positions.py
          echo '    host = "https://clob.polymarket.com"' >> get_positions.py
          echo '    key = os.environ.get("PRIVATE_KEY")' >> get_positions.py
          echo '    ' >> get_positions.py
          echo '    print(f"使用私钥: {key[:4]}...{key[-4:] if key else \'未设置\'}")' >> get_positions.py
          echo '    ' >> get_positions.py
          echo '    try:' >> get_positions.py
          echo '        # 初始化客户端' >> get_positions.py
          echo '        print("正在初始化Polymarket客户端...")' >> get_positions.py
          echo '        client = ClobClient(' >> get_positions.py
          echo '            host=host,' >> get_positions.py
          echo '            key=key,' >> get_positions.py
          echo '            chain_id=POLYGON' >> get_positions.py
          echo '        )' >> get_positions.py
          echo '        ' >> get_positions.py
          echo '        # 设置API凭据' >> get_positions.py
          echo '        print("设置API凭据...")' >> get_positions.py
          echo '        creds = load_api_credentials()' >> get_positions.py
          echo '        print(f"API密钥: {creds[\'apiKey\']}")' >> get_positions.py
          echo '        client.set_api_creds(creds)' >> get_positions.py
          echo '        ' >> get_positions.py
          echo '        # 获取钱包地址' >> get_positions.py
          echo '        if hasattr(client, "get_address"):' >> get_positions.py
          echo '            try:' >> get_positions.py
          echo '                address = client.get_address()' >> get_positions.py
          echo '                print(f"钱包地址: {address}")' >> get_positions.py
          echo '            except:' >> get_positions.py
          echo '                print("无法获取钱包地址")' >> get_positions.py
          echo '        ' >> get_positions.py
          echo '        return client' >> get_positions.py
          echo '    except Exception as e:' >> get_positions.py
          echo '        print(f"初始化客户端时出错: {str(e)}")' >> get_positions.py
          echo '        import traceback' >> get_positions.py
          echo '        print(traceback.format_exc())' >> get_positions.py
          echo '        return None' >> get_positions.py
          echo '' >> get_positions.py
          
          echo 'def get_positions_direct_api(client):' >> get_positions.py
          echo '    """直接使用HTTP请求获取持仓"""' >> get_positions.py
          echo '    try:' >> get_positions.py
          echo '        print("尝试通过直接HTTP请求获取持仓...")' >> get_positions.py
          echo '        ' >> get_positions.py
          echo '        # 准备凭据' >> get_positions.py
          echo '        creds = load_api_credentials()' >> get_positions.py
          echo '        api_key = creds["apiKey"]' >> get_positions.py
          echo '        secret = creds["secret"]' >> get_positions.py
          echo '        passphrase = creds["passphrase"]' >> get_positions.py
          echo '        ' >> get_positions.py
          echo '        # 准备请求头' >> get_positions.py
          echo '        headers = {' >> get_positions.py
          echo '            "Content-Type": "application/json",' >> get_positions.py
          echo '            "X-API-KEY": api_key,' >> get_positions.py
          echo '            "X-API-SECRET": secret,' >> get_positions.py
          echo '            "X-API-PASSPHRASE": passphrase' >> get_positions.py
          echo '        }' >> get_positions.py
          echo '        ' >> get_positions.py
          echo '        # 尝试不同的API端点' >> get_positions.py
          echo '        endpoints = [' >> get_positions.py
          echo '            "/portfolio",' >> get_positions.py
          echo '            "/positions",' >> get_positions.py
          echo '            "/user/positions",' >> get_positions.py
          echo '            "/user/portfolio"' >> get_positions.py
          echo '        ]' >> get_positions.py
          echo '        ' >> get_positions.py
          echo '        host = "https://clob.polymarket.com"' >> get_positions.py
          echo '        ' >> get_positions.py
          echo '        for endpoint in endpoints:' >> get_positions.py
          echo '            url = f"{host}{endpoint}"' >> get_positions.py
          echo '            print(f"请求URL: {url}")' >> get_positions.py
          echo '            ' >> get_positions.py
          echo '            response = requests.get(url, headers=headers)' >> get_positions.py
          echo '            print(f"响应状态码: {response.status_code}")' >> get_positions.py
          echo '            ' >> get_positions.py
          echo '            try:' >> get_positions.py
          echo '                data = response.json()' >> get_positions.py
          echo '                print(f"响应内容: {json.dumps(data, indent=2)}")' >> get_positions.py
          echo '            except:' >> get_positions.py
          echo '                print(f"响应内容无法解析为JSON: {response.text}")' >> get_positions.py
          echo '            ' >> get_positions.py
          echo '            print("-" * 50)' >> get_positions.py
          echo '        ' >> get_positions.py
          echo '        return True' >> get_positions.py
          echo '    except Exception as e:' >> get_positions.py
          echo '        print(f"直接请求API时出错: {str(e)}")' >> get_positions.py
          echo '        import traceback' >> get_positions.py
          echo '        print(traceback.format_exc())' >> get_positions.py
          echo '        return False' >> get_positions.py
          echo '' >> get_positions.py
          
          echo 'def main():' >> get_positions.py
          echo '    """主函数"""' >> get_positions.py
          echo '    print("=== Polymarket持仓查询工具 ===")' >> get_positions.py
          echo '    print(f"当前时间: {time.strftime(\"%Y-%m-%d %H:%M:%S\")}")' >> get_positions.py
          echo '    ' >> get_positions.py
          echo '    # 初始化客户端' >> get_positions.py
          echo '    client = get_client_info()' >> get_positions.py
          echo '    ' >> get_positions.py
          echo '    # 通过直接HTTP请求获取持仓' >> get_positions.py
          echo '    get_positions_direct_api(client)' >> get_positions.py
          echo '    ' >> get_positions.py
          echo '    print("\\n查询完成，请查看上面的结果。")' >> get_positions.py
          echo '' >> get_positions.py
          
          echo 'if __name__ == "__main__":' >> get_positions.py
          echo '    main()' >> get_positions.py
      
      - name: Run position script
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          python get_positions.py
