name: Explore Polymarket API

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  explore-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py-clob-client
      
      - name: Create API exploration script - Part 1
        run: |
          echo '#!/usr/bin/env python3' > explore_api.py
          echo 'import os' >> explore_api.py
          echo 'import json' >> explore_api.py
          echo 'import time' >> explore_api.py
          echo 'from py_clob_client.client import ClobClient' >> explore_api.py
          echo 'from py_clob_client.constants import POLYGON' >> explore_api.py
          echo 'from py_clob_client.clob_types import OrderArgs' >> explore_api.py
          echo 'from py_clob_client.order_builder.constants import BUY, SELL' >> explore_api.py
          echo '' >> explore_api.py
          
      - name: Create API exploration script - Part 2
        run: |
          echo 'def load_api_credentials(credentials_file=None):' >> explore_api.py
          echo '    """' >> explore_api.py
          echo '    加载API凭据，可以从文件或手动设置' >> explore_api.py
          echo '    """' >> explore_api.py
          echo '    return {' >> explore_api.py
          echo '        "apiKey": "4f812fe9-b869-c71c-7afb-08f36a0365eb",' >> explore_api.py
          echo '        "secret": "TW2vuAaOqb1cnfS2OJvnAM-LvLNUMIAurWi65BPco_I=",' >> explore_api.py
          echo '        "passphrase": "bebaa3341759979518ec045595847d64f5b826413b0cdb485d46bd84fa0c951b"' >> explore_api.py
          echo '    }' >> explore_api.py
          echo '' >> explore_api.py
          
      - name: Create API exploration script - Part 3
        run: |
          echo 'def get_client():' >> explore_api.py
          echo '    """初始化并返回Polymarket客户端"""' >> explore_api.py
          echo '    host = "https://clob.polymarket.com"' >> explore_api.py
          echo '    key = os.environ.get("PRIVATE_KEY")' >> explore_api.py
          echo '    try:' >> explore_api.py
          echo '        print("正在初始化Polymarket客户端...")' >> explore_api.py
          echo '        client = ClobClient(host=host, key=key, chain_id=POLYGON)' >> explore_api.py
          echo '        print("设置API凭据...")' >> explore_api.py
          echo '        creds = load_api_credentials()' >> explore_api.py
          echo '        client.set_api_creds(creds)' >> explore_api.py
          echo '        return client' >> explore_api.py
          echo '    except Exception as e:' >> explore_api.py
          echo '        print(f"初始化客户端时出错: {str(e)}")' >> explore_api.py
          echo '        return None' >> explore_api.py
          echo '' >> explore_api.py
          
      - name: Create API exploration script - Part 4
        run: |
          echo 'def list_methods(client):' >> explore_api.py
          echo '    """列出客户端可用的所有方法"""' >> explore_api.py
          echo '    print("\\n=== 可用的客户端方法 ===")' >> explore_api.py
          echo '    methods = [method for method in dir(client) if not method.startswith("_")]' >> explore_api.py
          echo '    methods.sort()' >> explore_api.py
          echo '    for method in methods:' >> explore_api.py
          echo '        print(f"- {method}")' >> explore_api.py
          echo '' >> explore_api.py
          
      - name: Create API exploration script - Part 5
        run: |
          echo 'def main():' >> explore_api.py
          echo '    """主函数"""' >> explore_api.py
          echo '    print("=== Polymarket API探索工具 ===")' >> explore_api.py
          echo '    client = get_client()' >> explore_api.py
          echo '    if client:' >> explore_api.py
          echo '        list_methods(client)' >> explore_api.py
          echo '        # 尝试执行一些无参数的方法' >> explore_api.py
          echo '        try_methods = ["get_orders", "get_balances", "get_markets"]' >> explore_api.py
          echo '        for method in try_methods:' >> explore_api.py
          echo '            if hasattr(client, method):' >> explore_api.py
          echo '                try:' >> explore_api.py
          echo '                    print(f"\\n尝试执行{method}方法...")' >> explore_api.py
          echo '                    result = getattr(client, method)()' >> explore_api.py
          echo '                    print(f"结果类型: {type(result)}")' >> explore_api.py
          echo '                    print(f"结果内容: {result}")' >> explore_api.py
          echo '                except Exception as e:' >> explore_api.py
          echo '                    print(f"执行{method}失败: {str(e)}")' >> explore_api.py
          echo '            else:' >> explore_api.py
          echo '                print(f"客户端没有{method}方法")' >> explore_api.py
          echo '    else:' >> explore_api.py
          echo '        print("客户端初始化失败")' >> explore_api.py
          echo '' >> explore_api.py
          echo 'if __name__ == "__main__":' >> explore_api.py
          echo '    main()' >> explore_api.py
          
      - name: Show script content
        run: |
          cat explore_api.py
          
      - name: Run API exploration script
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          python explore_api.py
